
# attrgram_parser_tab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEDIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMES XINPexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorfactor : NUMBER \n                | XINPfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'NUMBER':([0,6,7,8,9,10,],[4,4,4,4,4,4,]),'XINP':([0,6,7,8,9,10,],[5,5,5,5,5,5,]),'LPAREN':([0,6,7,8,9,10,],[6,6,6,6,6,6,]),'$end':([1,2,3,4,5,12,13,14,15,16,],[0,-3,-6,-7,-8,-1,-2,-4,-5,-9,]),'PLUS':([1,2,3,4,5,11,12,13,14,15,16,],[7,-3,-6,-7,-8,7,-1,-2,-4,-5,-9,]),'MINUS':([1,2,3,4,5,11,12,13,14,15,16,],[8,-3,-6,-7,-8,8,-1,-2,-4,-5,-9,]),'RPAREN':([2,3,4,5,11,12,13,14,15,16,],[-3,-6,-7,-8,16,-1,-2,-4,-5,-9,]),'TIMES':([2,3,4,5,12,13,14,15,16,],[9,-6,-7,-8,9,9,-4,-5,-9,]),'DIVIDE':([2,3,4,5,12,13,14,15,16,],[10,-6,-7,-8,10,10,-4,-5,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,6,],[1,11,]),'term':([0,6,7,8,],[2,2,12,13,]),'factor':([0,6,7,8,9,10,],[3,3,3,3,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser.py',32),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','parser.py',36),
  ('expression -> term','expression',1,'p_expression_term','parser.py',40),
  ('term -> term TIMES factor','term',3,'p_term_times','parser.py',44),
  ('term -> term DIVIDE factor','term',3,'p_term_div','parser.py',48),
  ('term -> factor','term',1,'p_term_factor','parser.py',52),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser.py',56),
  ('factor -> XINP','factor',1,'p_factor_num','parser.py',57),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',61),
]
